#- name: add webupd8team
#  shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{ ansible_distribution_release }} main" | tee -a /etc/apt/sources.list
#  sudo: yes

#- name: add key server
#  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
#  sudo: yes
- name: Prevent apt repository caching for download.oracle.com
  lineinfile: dest=/etc/apt/apt.conf.d/99proxy regexp="^Acquire::http::Proxy\s*{\s*download.oracle.com DIRECT\s*;\s*}\s*;\s*" line="Acquire::http::Proxy { download.oracle.com DIRECT; };" state=present create=yes

- name: Install software-properties-common
  apt: pkg=software-properties-common state=present update_cache=yes
  sudo: yes 
    
- name: Install python-software-properties
  apt: pkg=python-software-properties state=present update_cache=yes
  sudo: yes 
  when: ansible_distribution_release == "precise"

- name: Add webupd8team/java PPA
  apt_repository: repo="ppa:webupd8team/java"

- name: Refresh apt
  shell: apt-get update
  sudo: yes

- name: Auto-accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: Install java8
  apt: name=oracle-java8-installer state=present
  sudo: yes

- name: Install ca-certificates
  apt: name=ca-certificates state=present
  sudo: yes
